modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT License"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]] #mandatory
modId="turtlechargingstation" #mandatory
version="1.0.0-1.18.2" #mandatory
displayName="Turtle Charging Station" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="turtlechargingstationlogo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Miki Tellurium" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
description='''Adds a block that can charge CC:Tweaked turtles using Forge Energy'''

[[dependencies.turtlechargingstation]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.turtlechargingstation]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.turtlechargingstation]]
modId="computercraft"
mandatory=true
versionRange="[1.101.2,1.102)"
ordering="NONE"
side="BOTH"
